services:
  - type: web
    name: cctv-pdf
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: gunicorn app:app
